# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d8460c2cabf3a937bbcc083ee9d5794590c6af8e8a3a4f2e5eeaa1be726b25fc138b5e1ead6f2e0ffb14decc8a63a6f9cf8c1aa657892fa88b5444bff7d0c32

test:
  secret_key_base: 16aa244f21404a1528e4f1c075e3d59867bdb6b277a0b65b5bcd5b57ccf0b08ea761ed4ca38b4cffbb47c3cc96ba7f43090a5e9b023030427378c956484b6037

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
